### ISSUE TITLE
Text sent in visual mode breaks if empty line

### ISSUE THREAD

**Issue by robertocarta** [HiPhish/repl.nvim#1]
For example:
```
 6 class MyDataFrame:
 7     def __init__(self):
 8         self.df = pd.DataFrame()
 9
10     def transform(self, x):
12         return self.df*x
```

If I select all the code above, only lines 6,7, and 8 will be sent

**Comment by HiPhish** [comment]
This is a limitation of the Pyton REPL, when text is sent over it is sent line by line. Try typing those lines one by one into the REPL and you will get an error about unexpected indentation.

```python
Python 3.6.2 (default, Jul 17 2017, 16:44:47)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class MyDataFrame:
...     def __init__(self):
...             self.df = "2"
...
>>>     def transform(self, x:
  File "<stdin>", line 1
    def transform(self, x:
    ^
IndentationError: unexpected indent
```

This would not be happening the the blank line on line 9 would contain spaces to maintain the indentation

**Comment by robertocarta** [comment]
I think we should have a middle step where if there are empty lines in the selection they are temporarily deleted before being sent to the REPL

**Comment by HiPhish** [comment]
@robertocarta Sounds reasonable for Python, but I am not sure if this should be enforced for every type. As for filtering out blank lines, what do you think about this:
```vim
let l:text = join(filter(split(l:text, '\n'), {idx, val -> !empty(val)}), "\n")
```
This splits lines at line breaks and filters out the empty ones before joining them all back together with a line break.

**Comment by robertocarta** [comment]
Tried, it works perfectly! If you put if after an if statement to check the filtetype it would solve everything.

**Comment by HiPhish** [comment]
I think a better idea would be to add a per-filetype configuration for a text preprocessing function and then add this code to the Python REPL function. I want to avoid polluting the core of the plugin with any `if &ft =~? ...` blocks.

**Comment by HiPhish** [comment]
@robertocarta I have added the setting now and blank lines will be removed out of the box for Python. The fix is up already on GitLab, if you use the GitHub mirror here it will take a while for the mirror to catch up.
